apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/swe645hw2dep"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-10-31T01:00:21Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"55cd5991-5903-434f-a2b5-c4432cb76b2a"}: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: agent
    operation: Update
    time: "2022-10-31T01:00:21Z"
  name: swe645hw2dep
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: swe645hw2dep
    uid: 55cd5991-5903-434f-a2b5-c4432cb76b2a
  resourceVersion: "1954"
  uid: b9c5b042-a99b-44b7-9955-fbf8048c2b86
spec:
  clusterIP: 10.43.241.142
  clusterIPs:
  - 10.43.241.142
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: swe645hw2lb
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-swe645hw2dep
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
